# Interactive shell check
case $- in
*i*) ;;
*) return ;;
esac

BASH_CONFIG_DIR="$(dirname "$BASH_SOURCE")/bash"

if [[ -d "$BASH_CONFIG_DIR" ]]; then
	for file in "$BASH_CONFIG_DIR"/[0-9][0-9]-*; do
		[ -r "$file" ] && source "$file"
	done
else
	PS1='\u@\h:\w\$ '
	echo "ERROR: Configuration directory not found: $BASH_CONFIG_DIR" >&2
fi
